name: CI/CD Pipeline

on:
  push:
    branches:
      - main2  # Change to your branch name
  pull_request:
    branches:
      - main2  # Change to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GRC-incident_2606/backend/requirements.txt

      # Snyk security test for vulnerabilities
      - name: Snyk Security Test
        uses: snyk/actions/python@master
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}  # Add your Snyk token to GitHub secrets

      # Deploy to AWS EC2 using SSH
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}  # Add EC2 host IP to GitHub secrets
          username: ${{ secrets.AWS_EC2_USER }}  # EC2 username, like 'ec2-user' or 'ubuntu'
          key: ${{ secrets.AWS_EC2_SSH_KEY }}  # Add EC2 private SSH key to GitHub secrets
          script: |
            cd /path/to/your/app
            git pull origin main2  # Pull the latest changes from the 'main2' branch
            # Restart application service (if any)
            sudo systemctl restart your-app-service

      # Send email notifications
      - name: Send Email Notification
        run: |
          echo "Build and Deployment Success!" | mail -s "CI/CD Pipeline Status" srilakshmi.a@vardaanglobal.com
